USE MPMS;
GO

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

-- 1. 升級 dbo.MPMS_TASK
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_TASK') AND name = 'row_version')
BEGIN
    ALTER TABLE dbo.MPMS_TASK ADD row_version ROWVERSION NOT NULL;
END;
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_TASK') AND name = 'review_round')
BEGIN
    ALTER TABLE dbo.MPMS_TASK ADD review_round INT NOT NULL DEFAULT 0;
END;
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_TASK') AND name = 'current_review_id')
BEGIN
    ALTER TABLE dbo.MPMS_TASK ADD current_review_id INT NULL;
END;
GO

-- 2. 升級 dbo.MPMS_TASK_REVIEW
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_TASK_REVIEW') AND name = 'row_version')
BEGIN
    ALTER TABLE dbo.MPMS_TASK_REVIEW ADD row_version ROWVERSION NOT NULL;
END;
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_TASK_REVIEW') AND name = 'review_round')
BEGIN
    ALTER TABLE dbo.MPMS_TASK_REVIEW ADD review_round INT NOT NULL DEFAULT 1;
END;
GO

-- 為 MPMS_TASK.current_review_id 新增外鍵限制（如果不存在）
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MPMS_TASK_CURRENT_REVIEW')
BEGIN
    ALTER TABLE dbo.MPMS_TASK ADD CONSTRAINT FK_MPMS_TASK_CURRENT_REVIEW FOREIGN KEY (current_review_id) REFERENCES dbo.MPMS_TASK_REVIEW(review_id);
END;
GO

-- 建立 filtered unique index UX_TASK_REVIEW_PENDING
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_TASK_REVIEW_PENDING' AND object_id = OBJECT_ID('dbo.MPMS_TASK_REVIEW'))
BEGIN
    DROP INDEX UX_TASK_REVIEW_PENDING ON dbo.MPMS_TASK_REVIEW;
END;
GO
CREATE UNIQUE NONCLUSTERED INDEX UX_TASK_REVIEW_PENDING
ON dbo.MPMS_TASK_REVIEW (task_id)
WHERE review_result = 'Pending';
GO

-- 3. 升級 dbo.MPMS_TASK_ATTACHMENT
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_TASK_ATTACHMENT') AND name = 'visibility_type')
BEGIN
    ALTER TABLE dbo.MPMS_TASK_ATTACHMENT ADD visibility_type VARCHAR(30) NOT NULL DEFAULT 'Public';
END;
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_TASK_ATTACHMENT') AND name = 'scan_status')
BEGIN
    ALTER TABLE dbo.MPMS_TASK_ATTACHMENT ADD scan_status VARCHAR(20) NOT NULL DEFAULT 'Passed';
END;
GO

-- 4. 升級 dbo.MPMS_WEEKLY_SNAPSHOT
-- 移除舊快照關聯，以防舊資料干擾
DELETE FROM dbo.MPMS_SNAPSHOT_TASK;
DELETE FROM dbo.MPMS_SNAPSHOT_MILESTONE;
DELETE FROM dbo.MPMS_SNAPSHOT_PROJECT;
DELETE FROM dbo.MPMS_WEEKLY_SNAPSHOT;
GO

-- 移除現有外鍵以方便欄位調整
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MPMS_SNAPSHOT_MEETING')
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT DROP CONSTRAINT FK_MPMS_SNAPSHOT_MEETING;
GO
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MPMS_SNAPSHOT_USER')
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT DROP CONSTRAINT FK_MPMS_SNAPSHOT_USER;
GO
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MPMS_WEEKLY_SNAPSHOT_PROJECT')
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT DROP CONSTRAINT FK_MPMS_WEEKLY_SNAPSHOT_PROJECT;
GO
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MPMS_WEEKLY_SNAPSHOT_MEETING')
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT DROP CONSTRAINT FK_MPMS_WEEKLY_SNAPSHOT_MEETING;
GO
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MPMS_WEEKLY_SNAPSHOT_USER')
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT DROP CONSTRAINT FK_MPMS_WEEKLY_SNAPSHOT_USER;
GO
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MPMS_WEEKLY_SNAPSHOT_PARENT')
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT DROP CONSTRAINT FK_MPMS_WEEKLY_SNAPSHOT_PARENT;
GO

-- 重命名欄位 (如果舊欄位還存在)
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT') AND name = 'snapshot_week')
BEGIN
    EXEC sp_rename 'dbo.MPMS_WEEKLY_SNAPSHOT.snapshot_week', 'week_code', 'COLUMN';
END;
GO
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT') AND name = 'snapshot_version')
BEGIN
    EXEC sp_rename 'dbo.MPMS_WEEKLY_SNAPSHOT.snapshot_version', 'snapshot_version_no', 'COLUMN';
END;
GO
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT') AND name = 'revision_reason')
BEGIN
    EXEC sp_rename 'dbo.MPMS_WEEKLY_SNAPSHOT.revision_reason', 'correction_reason', 'COLUMN';
END;
GO
IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT') AND name = 'sealed_at')
BEGIN
    EXEC sp_rename 'dbo.MPMS_WEEKLY_SNAPSHOT.sealed_at', 'sealed_at_utc', 'COLUMN';
END;
GO

-- 移除 is_revision 預設值約束與欄位 (寫在同一個 GO 中避免變更範圍問題)
DECLARE @ConstraintName NVARCHAR(200);
DECLARE @SQL NVARCHAR(MAX);
SELECT @ConstraintName = name
FROM sys.default_constraints
WHERE parent_object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT')
  AND parent_column_id = COLUMNPROPERTY(OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT'), 'is_revision', 'ColumnId');

IF @ConstraintName IS NOT NULL
BEGIN
    SET @SQL = 'ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT DROP CONSTRAINT ' + @ConstraintName;
    EXEC sp_executesql @SQL;
END;
GO

IF EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT') AND name = 'is_revision')
BEGIN
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT DROP COLUMN is_revision;
END;
GO

-- 新增 V0.5 欄位
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT') AND name = 'snapshot_type')
BEGIN
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT ADD snapshot_type VARCHAR(20) NOT NULL DEFAULT 'Normal';
END;
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT') AND name = 'project_id')
BEGIN
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT ADD project_id INT NOT NULL;
END;
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT') AND name = 'period_start_at_utc')
BEGIN
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT ADD period_start_at_utc DATETIME2 NOT NULL DEFAULT GETDATE();
END;
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT') AND name = 'period_end_at_utc')
BEGIN
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT ADD period_end_at_utc DATETIME2 NOT NULL DEFAULT GETDATE();
END;
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT') AND name = 'is_current_version')
BEGIN
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT ADD is_current_version BIT NOT NULL DEFAULT 1;
END;
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT') AND name = 'parent_snapshot_id')
BEGIN
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT ADD parent_snapshot_id INT NULL;
END;
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT') AND name = 'snapshot_note')
BEGIN
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT ADD snapshot_note NVARCHAR(MAX) NULL;
END;
GO

-- 重新建立外鍵
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MPMS_WEEKLY_SNAPSHOT_PROJECT')
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT ADD CONSTRAINT FK_MPMS_WEEKLY_SNAPSHOT_PROJECT FOREIGN KEY (project_id) REFERENCES dbo.MPMS_PROJECT(project_id);
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MPMS_WEEKLY_SNAPSHOT_MEETING')
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT ADD CONSTRAINT FK_MPMS_WEEKLY_SNAPSHOT_MEETING FOREIGN KEY (meeting_id) REFERENCES dbo.MPMS_MEETING(meeting_id);
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MPMS_WEEKLY_SNAPSHOT_USER')
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT ADD CONSTRAINT FK_MPMS_WEEKLY_SNAPSHOT_USER FOREIGN KEY (sealed_by) REFERENCES dbo.MPMS_USER(user_id);
GO

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_MPMS_WEEKLY_SNAPSHOT_PARENT')
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT ADD CONSTRAINT FK_MPMS_WEEKLY_SNAPSHOT_PARENT FOREIGN KEY (parent_snapshot_id) REFERENCES dbo.MPMS_WEEKLY_SNAPSHOT(snapshot_id);
GO

-- 建立唯一性約束
IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'UX_PROJECT_WEEK_VERSION' AND parent_object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT'))
BEGIN
    ALTER TABLE dbo.MPMS_WEEKLY_SNAPSHOT ADD CONSTRAINT UX_PROJECT_WEEK_VERSION UNIQUE (project_id, week_code, snapshot_version_no);
END;
GO

IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'UX_PROJECT_WEEK_CURRENT' AND object_id = OBJECT_ID('dbo.MPMS_WEEKLY_SNAPSHOT'))
BEGIN
    DROP INDEX UX_PROJECT_WEEK_CURRENT ON dbo.MPMS_WEEKLY_SNAPSHOT;
END;
GO
CREATE UNIQUE NONCLUSTERED INDEX UX_PROJECT_WEEK_CURRENT
ON dbo.MPMS_WEEKLY_SNAPSHOT (project_id, week_code)
WHERE is_current_version = 1;
GO

-- 5. 新增 CK_TASK_ASSIST_NOT_OWNER 跨表防呆觸發器
IF EXISTS (SELECT * FROM sys.triggers WHERE name = 'TR_TASK_ASSIST_OWNER_CHECK' AND parent_id = OBJECT_ID('dbo.MPMS_TASK_ASSIST'))
BEGIN
    DROP TRIGGER dbo.TR_TASK_ASSIST_OWNER_CHECK;
END;
GO
CREATE TRIGGER dbo.TR_TASK_ASSIST_OWNER_CHECK
ON dbo.MPMS_TASK_ASSIST
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1 
        FROM inserted i
        INNER JOIN dbo.MPMS_TASK t ON i.task_id = t.task_id
        WHERE i.assist_user_id = t.owner_user_id
    )
    BEGIN
        RAISERROR ('主辦負責人不可同時擔任協辦人員！', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO
